import "./globals.css";
import { Crimson_Pro } from "next/font/google";

const crismon = Crimson_Pro({ subsets: ["latin"] });

export const metadata = {
    title: "cicero",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${crismon.className} p-10 xl:p-36`}>
                {children}
            </body>
        </html>
    );
}
